### ISSUE TITLE
Convert course materials to AsciiDoc format

### ISSUE THREAD

**Issue by ronaldtse** [expresslang/course#5]
@manuel489 do you have time to help with this? Thanks!

**Comment by manuelfuenmayor** [comment]
@ronaldtse how would you like the structure of the converted files to be?
The tex files generate 14 pdf files:
````
advexpv.pdf
advexpvtn.pdf
answers.pdf
egcarsg.pdf
egcarsx.pdf
...
````
I was thinking on naming the adoc files like the pdfs in a folder apart.

**Comment by ronaldtse** [comment]
@manuel489 I think the names right now are too obscure, can you propose better names? Thanks!

**Comment by manuelfuenmayor** [comment]
@ronaldtse sure. I can use the title of the documents:

````
an_introduction_v.adoc
an_introduction_vtn.adoc
expressg_v.adoc
expressg_vtn.adoc
...
````

There are documents that have two versions, one with notes for the instructor (`vtn`) and other without the notes (`v`, convention taken from the *readme* file).
The course is divided six parts. So, I can create six folders to lodge the documents for better organization.

**Comment by ronaldtse** [comment]
@manuel489 I reviewed the content and let's do this instead:

* `expv` => `01-introduction.adoc`
* `expvtn` => `01-introduction-notes.adoc`

* `grexpv` => `02-express-g.adoc`
* `grexpvtn` => `02-express-g-notes.adoc`

* `advexpv` => `03-advanced-express.adoc`
* `advexpvtn` => `03-advanced-express-notes.adoc`

* `rulesv` => `04-express-rules.adoc`
* `rulesvtn` => `04-express-rules-notes.adoc`

* `principlesv` => `05-modelling-principles.adoc`

* `answers` => `06-modelling-answers.adoc`
* `exercises` => `06-modelling-exercises.adoc`

* `egcarsg` => `example-expg-cars.adoc`
* `egcarsx` => `example-exp-cars.adoc`
* `egspec` => `example-model-carreg.adoc`

**Comment by ronaldtse** [comment]
Split according to folder is a good idea, too.

**Comment by manuelfuenmayor** [comment]
OK
(Yeah, those names are certainly better, thanks 👍.)

**Comment by manuelfuenmayor** [comment]
@ronaldtse, in regards to the notes, these are shown in italics in the original PDFs:

![issue1](https://user-images.githubusercontent.com/33627611/150693470-73ea139f-a910-4665-881f-04ad0045be72.PNG)


Should we directly apply italic markup in AsciiDoc (i.e. `__text__`)
or use some block markup (like quote, for example) in order to differentiate this from normal content?

**Comment by ronaldtse** [comment]
We just need to retain the semantic information not the formatting, thanks @manuel489

**Comment by manuelfuenmayor** [comment]
Conversion added in https://github.com/expresslang/course/pull/6. Closing.
